// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dafyjymlebjmrxbecjvr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRhZnlqeW1sZWJqbXJ4YmVjanZyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwMzY0OTgsImV4cCI6MjA3MDYxMjQ5OH0.pH6aqaZTNWB2f8tojaoEijk_dQpFIzP8We3r_Bg6o6Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});